services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CSV_FILE_PATH=${CSV_FILE_PATH}
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./
          action: sync
          target: /app
